argo_repo: https://argoproj.github.io/argo-helm
argo_repo_name: argo
argo_chart_name: argo-cd

argo_chart_ref: https://raw.githubusercontent.com/mekanics/homelab/main/the-lab/bootstrap/argocd/Chart.yaml

# Action
argocd_action: present # Value : present / absent

# Namespace
argocd_k8s_namespace: argocd
